/*
 * Decompiled with CFR 0.152.
 *
 * Could not load the following classes:
 *  cpw.mods.fml.common.registry.GameRegistry
 *  net.minecraft.item.Item
 *  net.minecraft.item.Item$ToolMaterial
 *  net.minecraft.item.ItemArmor$ArmorMaterial
 *  net.minecraftforge.common.util.EnumHelper
 */
package com.krazykid1117.item;

import com.krazykid1117.CreativeTabs.MCreativeTabs;
import com.krazykid1117.item.Dynamite;
import com.krazykid1117.item.Grenade;
import com.krazykid1117.item.emAxe;
import com.krazykid1117.item.emHoe;
import com.krazykid1117.item.emPick;
import com.krazykid1117.item.emShovel;
import com.krazykid1117.item.emSword;
import com.krazykid1117.item.emarmor;
import com.krazykid1117.item.hrarmor;
import com.krazykid1117.item.joAxe;
import com.krazykid1117.item.joHoe;
import com.krazykid1117.item.joPick;
import com.krazykid1117.item.joShovel;
import com.krazykid1117.item.joSword;
import com.krazykid1117.item.oAxe;
import com.krazykid1117.item.oHoe;
import com.krazykid1117.item.oPick;
import com.krazykid1117.item.oShovel;
import com.krazykid1117.item.oSword;
import com.krazykid1117.item.obarmor;
import com.krazykid1117.item.oparmor;
import com.krazykid1117.item.opaxe;
import com.krazykid1117.item.oppick;
import com.krazykid1117.item.opshovel;
import com.krazykid1117.item.opsword;
import com.krazykid1117.item.rAxe;
import com.krazykid1117.item.rGAxe;
import com.krazykid1117.item.rGHoe;
import com.krazykid1117.item.rGPick;
import com.krazykid1117.item.rGShovel;
import com.krazykid1117.item.rGSword;
import com.krazykid1117.item.rHoe;
import com.krazykid1117.item.rPick;
import com.krazykid1117.item.rShovel;
import com.krazykid1117.item.rSword;
import com.krazykid1117.item.rgarmor;
import com.krazykid1117.item.semAxe;
import com.krazykid1117.item.semHoe;
import com.krazykid1117.item.semPick;
import com.krazykid1117.item.semShovel;
import com.krazykid1117.item.semSword;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraftforge.common.util.EnumHelper;

public class MItems {
    public static Item.ToolMaterial reiGold = EnumHelper.addToolMaterial((String)"Reinforced Gold", (int)2, (int)260, (float)14.0f, (float)2.5f, (int)30);
    public static Item.ToolMaterial Red = EnumHelper.addToolMaterial((String)"Redstone", (int)2, (int)190, (float)13.5f, (float)1.7f, (int)15);
    public static Item.ToolMaterial emerald = EnumHelper.addToolMaterial((String)"Emerald", (int)2, (int)400, (float)9.0f, (float)2.9f, (int)15);
    public static Item.ToolMaterial semerald = EnumHelper.addToolMaterial((String)"SmoothEmerald", (int)3, (int)1300, (float)13.0f, (float)4.5f, (int)23);
    public static Item.ToolMaterial Obsidian = EnumHelper.addToolMaterial((String)"Obsidian", (int)3, (int)1600, (float)15.0f, (float)4.0f, (int)10);
    public static Item.ToolMaterial JObsidian = EnumHelper.addToolMaterial((String)"Jagged Obsidian", (int)3, (int)1561, (float)12.0f, (float)3.2f, (int)5);
    public static Item.ToolMaterial OP = EnumHelper.addToolMaterial((String)"OP", (int)3, (int)10000, (float)199.0f, (float)500.0f, (int)900);
    public static ItemArmor.ArmorMaterial rgarmor = EnumHelper.addArmorMaterial((String)"Reinforced Gold Armor", (int)16, (int[])new int[]{3, 7, 6, 3}, (int)26);
    public static ItemArmor.ArmorMaterial obarmor = EnumHelper.addArmorMaterial((String)"Obsidian Armor", (int)40, (int[])new int[]{4, 8, 6, 4}, (int)8);
    public static ItemArmor.ArmorMaterial emarmor = EnumHelper.addArmorMaterial((String)"Emerald Armor", (int)35, (int[])new int[]{3, 8, 7, 3}, (int)13);
    public static ItemArmor.ArmorMaterial oparmor = EnumHelper.addArmorMaterial((String)"OP Armor", (int)50, (int[])new int[]{4, 9, 7, 4}, (int)30);
    public static ItemArmor.ArmorMaterial hrarmor = EnumHelper.addArmorMaterial((String)"Hardened Redstone Armor", (int)12, (int[])new int[]{2, 5, 4, 2}, (int)13);
    public static Item rGold;
    public static Item rGPick;
    public static Item rGAxe;
    public static Item rGShovel;
    public static Item rGSword;
    public static Item rGHoe;
    public static Item INugget;
    public static Item emPick;
    public static Item emAxe;
    public static Item emShovel;
    public static Item emSword;
    public static Item emHoe;
    public static Item ObShard;
    public static Item sEm;
    public static Item semPick;
    public static Item semAxe;
    public static Item semShovel;
    public static Item semSword;
    public static Item semHoe;
    public static Item oPick;
    public static Item oAxe;
    public static Item oShovel;
    public static Item oSword;
    public static Item oHoe;
    public static Item joPick;
    public static Item joAxe;
    public static Item joShovel;
    public static Item joSword;
    public static Item joHoe;
    public static Item ObIngot;
    public static Item opsword;
    public static Item oppick;
    public static Item rghelm;
    public static Item rgchest;
    public static Item rgpants;
    public static Item rgboots;
    public static Item obhelm;
    public static Item obchest;
    public static Item obpants;
    public static Item obboots;
    public static Item emhelm;
    public static Item emchest;
    public static Item empants;
    public static Item emboots;
    public static Item opaxe;
    public static Item opshovel;
    public static Item Dynamite;
    public static Item ophelm;
    public static Item opchest;
    public static Item oppants;
    public static Item opboots;
    public static Item rPick;
    public static Item rAxe;
    public static Item rShovel;
    public static Item rSword;
    public static Item rHoe;
    public static Item hred;
    public static Item hrhelm;
    public static Item hrchest;
    public static Item hrpants;
    public static Item hrboots;
    public static int rghelmID;
    public static int rgchestID;
    public static int rgpantsID;
    public static int rgbootsID;
    public static int obhelmID;
    public static int obchestID;
    public static int obpantsID;
    public static int obbootsID;
    public static int emhelmID;
    public static int emchestID;
    public static int empantsID;
    public static int embootsID;
    public static int ophelmID;
    public static int opchestID;
    public static int oppantsID;
    public static int opbootsID;
    public static int hrhelmID;
    public static int hrchestID;
    public static int hrpantsID;
    public static int hrbootsID;
    public static Item Grenade;

    public static void MainRegistry() {
        MItems.initializeItem();
        MItems.registerItem();
    }

    public static void initializeItem() {
        rGold = new Item().setUnlocalizedName("rGold").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:rGold");
        rGPick = new rGPick(reiGold).setUnlocalizedName("rGPick").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:RGoldPick");
        rGAxe = new rGAxe(reiGold).setUnlocalizedName("rGAxe").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:RGoldAxe");
        rGShovel = new rGShovel(reiGold).setUnlocalizedName("rGShovel").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:RGoldShovel");
        rGSword = new rGSword(reiGold).setUnlocalizedName("rGSword").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:RGoldSword");
        rGHoe = new rGHoe(reiGold).setUnlocalizedName("rGHoe").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:RGoldHoe");
        INugget = new Item().setUnlocalizedName("INugget").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:IronNugget");
        emPick = new emPick(emerald).setUnlocalizedName("emPick").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:jEMPick");
        emAxe = new emAxe(emerald).setUnlocalizedName("emAxe").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:jEMAxe");
        emShovel = new emShovel(emerald).setUnlocalizedName("emShovel").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:jEMShovel");
        emSword = new emSword(emerald).setUnlocalizedName("emSword").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:jEMSword");
        emHoe = new emHoe(emerald).setUnlocalizedName("emHoe").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:jEMHoe");
        ObShard = new Item().setUnlocalizedName("ObShard").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:ObShard");
        sEm = new Item().setUnlocalizedName("sEm").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:sEm");
        semPick = new semPick(semerald).setUnlocalizedName("semPick").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:EMPick");
        semAxe = new semAxe(semerald).setUnlocalizedName("semAxe").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:EMAxe");
        semShovel = new semShovel(semerald).setUnlocalizedName("semShovel").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:EMShovel");
        semSword = new semSword(semerald).setUnlocalizedName("semSword").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:EMSword");
        semHoe = new semHoe(semerald).setUnlocalizedName("semHoe").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:EMHoe");
        oPick = new oPick(Obsidian).setUnlocalizedName("oPick").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:oPick");
        oAxe = new oAxe(Obsidian).setUnlocalizedName("oAxe").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:oAxe");
        oShovel = new oShovel(Obsidian).setUnlocalizedName("oShovel").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:oShovel");
        oSword = new oSword(Obsidian).setUnlocalizedName("oSword").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:oSword");
        oHoe = new oHoe(Obsidian).setUnlocalizedName("oHoe").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:oHoe");
        joPick = new joPick(JObsidian).setUnlocalizedName("joPick").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:joPick");
        joAxe = new joAxe(JObsidian).setUnlocalizedName("joAxe").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:joAxe");
        joShovel = new joShovel(JObsidian).setUnlocalizedName("joShovel").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:joShovel");
        joSword = new joSword(JObsidian).setUnlocalizedName("joSword").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:joSword");
        joHoe = new joHoe(JObsidian).setUnlocalizedName("joHoe").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:joHoe");
        ObIngot = new Item().setUnlocalizedName("ObIngot").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:ObIngot");
        opsword = new opsword(OP).setUnlocalizedName("opsword").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:OPS");
        oppick = new oppick(OP).setUnlocalizedName("oppick").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:OPP");
        opaxe = new opaxe(OP).setUnlocalizedName("opaxe").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:OPA");
        opshovel = new opshovel(OP).setUnlocalizedName("opshovel").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:OPSh");
        Dynamite = new Dynamite().setUnlocalizedName("Dynamite").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:Dynamite");
        rPick = new rPick(Red).setUnlocalizedName("rPick").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:rPick");
        rAxe = new rAxe(Red).setUnlocalizedName("rAxe").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:rAxe");
        rShovel = new rShovel(Red).setUnlocalizedName("rShovel").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:rShovel");
        rSword = new rSword(Red).setUnlocalizedName("rSword").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:rSword");
        rHoe = new rHoe(Red).setUnlocalizedName("rHoe").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:rHoe");
        hred = new Item().setUnlocalizedName("hred").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:hred");
        rghelm = new rgarmor(rgarmor, rghelmID, 0).setUnlocalizedName("rghelm").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:rghelmet");
        rgchest = new rgarmor(rgarmor, rgchestID, 1).setUnlocalizedName("rgchest").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:rgchest");
        rgpants = new rgarmor(rgarmor, rgpantsID, 2).setUnlocalizedName("rgpants").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:rgleggings");
        rgboots = new rgarmor(rgarmor, rgbootsID, 3).setUnlocalizedName("rgboots").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:rgboots");
        obhelm = new obarmor(obarmor, obhelmID, 0).setUnlocalizedName("obhelm").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:obhelmet");
        obchest = new obarmor(obarmor, obchestID, 1).setUnlocalizedName("obchest").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:obchest");
        obpants = new obarmor(obarmor, obpantsID, 2).setUnlocalizedName("obpants").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:obleggings");
        obboots = new obarmor(obarmor, obbootsID, 3).setUnlocalizedName("obboots").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:obboots");
        emhelm = new emarmor(emarmor, emhelmID, 0).setUnlocalizedName("emhelm").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:emhelmet");
        emchest = new emarmor(emarmor, emchestID, 1).setUnlocalizedName("emchest").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:emchest");
        empants = new emarmor(emarmor, empantsID, 2).setUnlocalizedName("empants").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:emleggings");
        emboots = new emarmor(emarmor, embootsID, 3).setUnlocalizedName("emboots").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:emboots");
        ophelm = new oparmor(oparmor, ophelmID, 0).setUnlocalizedName("ophelm").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:ophelmet");
        opchest = new oparmor(oparmor, opchestID, 1).setUnlocalizedName("opchest").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:opchest");
        oppants = new oparmor(oparmor, oppantsID, 2).setUnlocalizedName("oppants").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:opleggings");
        opboots = new oparmor(oparmor, opbootsID, 3).setUnlocalizedName("opboots").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:opboots");
        hrhelm = new hrarmor(hrarmor, hrhelmID, 0).setUnlocalizedName("hrhelm").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:hrhelmet");
        hrchest = new hrarmor(hrarmor, hrchestID, 1).setUnlocalizedName("hrchest").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:hrchest");
        hrpants = new hrarmor(hrarmor, hrpantsID, 2).setUnlocalizedName("hrpants").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:hrleggings");
        hrboots = new hrarmor(hrarmor, hrbootsID, 3).setUnlocalizedName("hrboots").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:hrboots");
        Grenade = new Grenade().setUnlocalizedName("Grenade").setCreativeTab(MCreativeTabs.tabToolsMod).setTextureName("usefultoolsmod:grenade");
    }

    public static void registerItem() {
        GameRegistry.registerItem((Item)rGPick, (String)rGPick.getUnlocalizedName());
        GameRegistry.registerItem((Item)rGAxe, (String)rGAxe.getUnlocalizedName());
        GameRegistry.registerItem((Item)rGShovel, (String)rGShovel.getUnlocalizedName());
        GameRegistry.registerItem((Item)rGSword, (String)rGSword.getUnlocalizedName());
        GameRegistry.registerItem((Item)rGHoe, (String)rGHoe.getUnlocalizedName());
        GameRegistry.registerItem((Item)rGold, (String)rGold.getUnlocalizedName());
        GameRegistry.registerItem((Item)INugget, (String)INugget.getUnlocalizedName());
        GameRegistry.registerItem((Item)emAxe, (String)emAxe.getUnlocalizedName());
        GameRegistry.registerItem((Item)emShovel, (String)emShovel.getUnlocalizedName());
        GameRegistry.registerItem((Item)emSword, (String)emSword.getUnlocalizedName());
        GameRegistry.registerItem((Item)emHoe, (String)emHoe.getUnlocalizedName());
        GameRegistry.registerItem((Item)emPick, (String)emPick.getUnlocalizedName());
        GameRegistry.registerItem((Item)ObShard, (String)ObShard.getUnlocalizedName());
        GameRegistry.registerItem((Item)sEm, (String)sEm.getUnlocalizedName());
        GameRegistry.registerItem((Item)semAxe, (String)semAxe.getUnlocalizedName());
        GameRegistry.registerItem((Item)semShovel, (String)semShovel.getUnlocalizedName());
        GameRegistry.registerItem((Item)semSword, (String)semSword.getUnlocalizedName());
        GameRegistry.registerItem((Item)semHoe, (String)semHoe.getUnlocalizedName());
        GameRegistry.registerItem((Item)semPick, (String)semPick.getUnlocalizedName());
        GameRegistry.registerItem((Item)oAxe, (String)oAxe.getUnlocalizedName());
        GameRegistry.registerItem((Item)oShovel, (String)oShovel.getUnlocalizedName());
        GameRegistry.registerItem((Item)oSword, (String)oSword.getUnlocalizedName());
        GameRegistry.registerItem((Item)oHoe, (String)oHoe.getUnlocalizedName());
        GameRegistry.registerItem((Item)oPick, (String)oPick.getUnlocalizedName());
        GameRegistry.registerItem((Item)joAxe, (String)joAxe.getUnlocalizedName());
        GameRegistry.registerItem((Item)joShovel, (String)joShovel.getUnlocalizedName());
        GameRegistry.registerItem((Item)joSword, (String)joSword.getUnlocalizedName());
        GameRegistry.registerItem((Item)joHoe, (String)joHoe.getUnlocalizedName());
        GameRegistry.registerItem((Item)joPick, (String)joPick.getUnlocalizedName());
        GameRegistry.registerItem((Item)ObIngot, (String)ObIngot.getUnlocalizedName());
        GameRegistry.registerItem((Item)opsword, (String)opsword.getUnlocalizedName());
        GameRegistry.registerItem((Item)oppick, (String)oppick.getUnlocalizedName());
        GameRegistry.registerItem((Item)opshovel, (String)opshovel.getUnlocalizedName());
        GameRegistry.registerItem((Item)opaxe, (String)opaxe.getUnlocalizedName());
        GameRegistry.registerItem((Item)Dynamite, (String)Dynamite.getUnlocalizedName());
        GameRegistry.registerItem((Item)rAxe, (String)rAxe.getUnlocalizedName());
        GameRegistry.registerItem((Item)rShovel, (String)rShovel.getUnlocalizedName());
        GameRegistry.registerItem((Item)rSword, (String)rSword.getUnlocalizedName());
        GameRegistry.registerItem((Item)rHoe, (String)rHoe.getUnlocalizedName());
        GameRegistry.registerItem((Item)rPick, (String)rPick.getUnlocalizedName());
        GameRegistry.registerItem((Item)hred, (String)hred.getUnlocalizedName());
        GameRegistry.registerItem((Item)rghelm, (String)rghelm.getUnlocalizedName());
        GameRegistry.registerItem((Item)rgchest, (String)rgchest.getUnlocalizedName());
        GameRegistry.registerItem((Item)rgpants, (String)rgpants.getUnlocalizedName());
        GameRegistry.registerItem((Item)rgboots, (String)rgboots.getUnlocalizedName());
        GameRegistry.registerItem((Item)obhelm, (String)obhelm.getUnlocalizedName());
        GameRegistry.registerItem((Item)obchest, (String)obchest.getUnlocalizedName());
        GameRegistry.registerItem((Item)obpants, (String)obpants.getUnlocalizedName());
        GameRegistry.registerItem((Item)obboots, (String)obboots.getUnlocalizedName());
        GameRegistry.registerItem((Item)emhelm, (String)emhelm.getUnlocalizedName());
        GameRegistry.registerItem((Item)emchest, (String)emchest.getUnlocalizedName());
        GameRegistry.registerItem((Item)empants, (String)empants.getUnlocalizedName());
        GameRegistry.registerItem((Item)emboots, (String)emboots.getUnlocalizedName());
        GameRegistry.registerItem((Item)ophelm, (String)ophelm.getUnlocalizedName());
        GameRegistry.registerItem((Item)opchest, (String)opchest.getUnlocalizedName());
        GameRegistry.registerItem((Item)oppants, (String)oppants.getUnlocalizedName());
        GameRegistry.registerItem((Item)opboots, (String)opboots.getUnlocalizedName());
        GameRegistry.registerItem((Item)hrhelm, (String)hrhelm.getUnlocalizedName());
        GameRegistry.registerItem((Item)hrchest, (String)hrchest.getUnlocalizedName());
        GameRegistry.registerItem((Item)hrpants, (String)hrpants.getUnlocalizedName());
        GameRegistry.registerItem((Item)hrboots, (String)hrboots.getUnlocalizedName());
        GameRegistry.registerItem((Item)Grenade, (String)Grenade.getUnlocalizedName());
    }
}
