// Generated by scripts/generate_config_descriptors.py. Do not edit by hand.
package com.stonytark.usefultoolsmod.client;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/** Canonical, loader-neutral metadata for all 126 persistent config options. */
public final class ConfigDescriptors {
    public record Descriptor(String key, String category, String label, String tooltip,
                             boolean reloadRequired) {}

    private static final Map<String, Descriptor> VALUES = build();

    private ConfigDescriptors() {}

    public static Descriptor get(String key) {
        Descriptor descriptor = VALUES.get(key);
        if (descriptor == null) throw new IllegalArgumentException("Unknown config option: " + key);
        return descriptor;
    }

    public static Map<String, Descriptor> values() {
        return VALUES;
    }

    private static Map<String, Descriptor> build() {
        Map<String, Descriptor> values = new LinkedHashMap<>();
        add(values, "explosivesEnabled", "Content Sets", "Explosives", "Controls explosives behavior.", false);
        add(values, "obsidianEnabled", "Content Sets", "Obsidian", "Controls obsidian behavior.", false);
        add(values, "emeraldEnabled", "Content Sets", "Emerald", "Controls emerald behavior.", false);
        add(values, "lapisEnabled", "Content Sets", "Lapis", "Controls lapis behavior.", false);
        add(values, "ferrousGoldEnabled", "Content Sets", "Ferrous Gold", "Controls ferrous gold behavior.", false);
        add(values, "hardenedRedstoneEnabled", "Content Sets", "Hardened Redstone", "Controls hardened redstone behavior.", false);
        add(values, "hardenedGlowstoneEnabled", "Content Sets", "Hardened Glowstone", "Controls hardened glowstone behavior.", false);
        add(values, "overpowerEnabled", "Content Sets", "Overpower", "Controls overpower behavior.", false);
        add(values, "ghostEnabled", "Content Sets", "Ghost", "Controls ghost behavior.", false);
        add(values, "spectralInfuserEnabled", "Content Sets", "Spectral Infuser", "Controls spectral infuser behavior.", false);
        add(values, "wraithEnabled", "Content Sets", "Wraith", "Controls wraith behavior.", false);
        add(values, "ectoplasmLanternEnabled", "Content Sets", "Ectoplasm Lantern", "Controls ectoplasm lantern behavior.", false);
        add(values, "spectralResonatorEnabled", "Content Sets", "Spectral Resonator", "Controls spectral resonator behavior.", false);
        add(values, "miningChargeEnabled", "Content Sets", "Mining Charge", "Controls mining charge behavior.", false);
        add(values, "stickyDynamiteEnabled", "Content Sets", "Sticky Dynamite", "Controls sticky dynamite behavior.", false);
        add(values, "remoteDetonationEnabled", "Content Sets", "Remote Detonation", "Controls remote detonation behavior.", false);
        add(values, "infusedToolEffects", "Effects", "Infused Tool", "Controls infused tool behavior.", false);
        add(values, "rawMetalRoughEnabled", "Content Sets", "Raw Metal Rough", "Controls raw metal rough behavior.", false);
        add(values, "roughCrystalEnabled", "Content Sets", "Rough Crystal", "Controls rough crystal behavior.", false);
        add(values, "snowEnabled", "Content Sets", "Snow", "Controls snow behavior.", false);
        add(values, "polishedCrystalEnabled", "Content Sets", "Polished Crystal", "Controls polished crystal behavior.", false);
        add(values, "iceEnabled", "Content Sets", "Ice", "Controls ice behavior.", false);
        add(values, "pprismEnabled", "Content Sets", "Pprism", "Controls pprism behavior.", false);
        add(values, "flintEnabled", "Content Sets", "Flint", "Controls flint behavior.", false);
        add(values, "fniEnabled", "Content Sets", "Fni", "Controls fni behavior.", false);
        add(values, "woodVariantsEnabled", "Content Sets", "Wood Variants", "Controls wood variants behavior.", false);
        add(values, "stoneVariantsEnabled", "Content Sets", "Stone Variants", "Controls stone variants behavior.", false);
        add(values, "paperEnabled", "Content Sets", "Paper", "Controls paper behavior.", false);
        add(values, "paperEffects", "Effects", "Paper", "Controls paper behavior.", false);
        add(values, "featherEnabled", "Content Sets", "Feather", "Controls feather behavior.", false);
        add(values, "featherEffects", "Effects", "Feather", "Controls feather behavior.", false);
        add(values, "glassEnabled", "Content Sets", "Glass", "Controls glass behavior.", false);
        add(values, "glassEffects", "Effects", "Glass", "Controls glass behavior.", false);
        add(values, "rabbitHideEnabled", "Content Sets", "Rabbit Hide", "Controls rabbit hide behavior.", false);
        add(values, "rabbitHideEffects", "Effects", "Rabbit Hide", "Controls rabbit hide behavior.", false);
        add(values, "cactusEnabled", "Content Sets", "Cactus", "Controls cactus behavior.", false);
        add(values, "cactusEffects", "Effects", "Cactus", "Controls cactus behavior.", false);
        add(values, "spongeEnabled", "Content Sets", "Sponge", "Controls sponge behavior.", false);
        add(values, "spongeEffects", "Effects", "Sponge", "Controls sponge behavior.", false);
        add(values, "boneEnabled", "Content Sets", "Bone", "Controls bone behavior.", false);
        add(values, "boneEffects", "Effects", "Bone", "Controls bone behavior.", false);
        add(values, "clayEnabled", "Content Sets", "Clay", "Controls clay behavior.", false);
        add(values, "clayEffects", "Effects", "Clay", "Controls clay behavior.", false);
        add(values, "netherWartEnabled", "Content Sets", "Nether Wart", "Controls nether wart behavior.", false);
        add(values, "netherWartEffects", "Effects", "Nether Wart", "Controls nether wart behavior.", false);
        add(values, "brickEnabled", "Content Sets", "Brick", "Controls brick behavior.", false);
        add(values, "netherBrickEnabled", "Content Sets", "Nether Brick", "Controls nether brick behavior.", false);
        add(values, "netherBrickEffects", "Effects", "Nether Brick", "Controls nether brick behavior.", false);
        add(values, "dripstoneEnabled", "Content Sets", "Dripstone", "Controls dripstone behavior.", false);
        add(values, "dripstoneEffects", "Effects", "Dripstone", "Controls dripstone behavior.", false);
        add(values, "copperEnabled", "Content Sets", "Copper", "Controls copper behavior.", false);
        add(values, "copperEffects", "Effects", "Copper", "Controls copper behavior.", false);
        add(values, "phantomEnabled", "Content Sets", "Phantom", "Controls phantom behavior.", false);
        add(values, "phantomEffects", "Effects", "Phantom", "Controls phantom behavior.", false);
        add(values, "magmaCreamEnabled", "Content Sets", "Magma Cream", "Controls magma cream behavior.", false);
        add(values, "magmaCreamEffects", "Effects", "Magma Cream", "Controls magma cream behavior.", false);
        add(values, "slimeEnabled", "Content Sets", "Slime", "Controls slime behavior.", false);
        add(values, "slimeEffects", "Effects", "Slime", "Controls slime behavior.", false);
        add(values, "blazeEnabled", "Content Sets", "Blaze", "Controls blaze behavior.", false);
        add(values, "blazeEffects", "Effects", "Blaze", "Controls blaze behavior.", false);
        add(values, "nautilusEnabled", "Content Sets", "Nautilus", "Controls nautilus behavior.", false);
        add(values, "nautilusEffects", "Effects", "Nautilus", "Controls nautilus behavior.", false);
        add(values, "purpurEnabled", "Content Sets", "Purpur", "Controls purpur behavior.", false);
        add(values, "purpurEffects", "Effects", "Purpur", "Controls purpur behavior.", false);
        add(values, "ghastTearEnabled", "Content Sets", "Ghast Tear", "Controls ghast tear behavior.", false);
        add(values, "ghastTearEffects", "Effects", "Ghast Tear", "Controls ghast tear behavior.", false);
        add(values, "eyeOfEnderEnabled", "Content Sets", "Eye Of Ender", "Controls eye of ender behavior.", false);
        add(values, "eyeOfEnderEffects", "Effects", "Eye Of Ender", "Controls eye of ender behavior.", false);
        add(values, "shulkerEnabled", "Content Sets", "Shulker", "Controls shulker behavior.", false);
        add(values, "shulkerEffects", "Effects", "Shulker", "Controls shulker behavior.", false);
        add(values, "turtleScuteEnabled", "Content Sets", "Turtle Scute", "Controls turtle scute behavior.", false);
        add(values, "turtleScuteEffects", "Effects", "Turtle Scute", "Controls turtle scute behavior.", false);
        add(values, "echoShardEnabled", "Content Sets", "Echo Shard", "Controls echo shard behavior.", false);
        add(values, "echoShardEffects", "Effects", "Echo Shard", "Controls echo shard behavior.", false);
        add(values, "dragonBreathEnabled", "Content Sets", "Dragon Breath", "Controls dragon breath behavior.", false);
        add(values, "dragonBreathEffects", "Effects", "Dragon Breath", "Controls dragon breath behavior.", false);
        add(values, "leatherEnabled", "Content Sets", "Leather", "Controls leather behavior.", false);
        add(values, "coalEnabled", "Content Sets", "Coal", "Controls coal behavior.", false);
        add(values, "cakeEnabled", "Food Sets", "Cake", "Controls cake behavior.", false);
        add(values, "foodHungerDrain", "Effects", "Food Hunger Drain", "Controls food hunger drain behavior.", false);
        add(values, "breadEnabled", "Food Sets", "Bread", "Controls bread behavior.", false);
        add(values, "breadArmorEffects", "Effects", "Bread Armor", "Controls bread armor behavior.", false);
        add(values, "driedKelpEnabled", "Food Sets", "Dried Kelp", "Controls dried kelp behavior.", false);
        add(values, "driedKelpArmorEffects", "Effects", "Dried Kelp Armor", "Controls dried kelp armor behavior.", false);
        add(values, "rottenFleshEnabled", "Food Sets", "Rotten Flesh", "Controls rotten flesh behavior.", false);
        add(values, "rottenFleshArmorEffects", "Effects", "Rotten Flesh Armor", "Controls rotten flesh armor behavior.", false);
        add(values, "rottenFleshUndeadNeutral", "Food Sets", "Rotten Flesh Undead Neutral", "Controls rotten flesh undead neutral behavior.", false);
        add(values, "melonEnabled", "Content Sets", "Melon", "Controls melon behavior.", false);
        add(values, "melonArmorEffects", "Effects", "Melon Armor", "Controls melon armor behavior.", false);
        add(values, "sweetBerryEnabled", "Food Sets", "Sweet Berry", "Controls sweet berry behavior.", false);
        add(values, "sweetBerryArmorEffects", "Effects", "Sweet Berry Armor", "Controls sweet berry armor behavior.", false);
        add(values, "sweetBerryThorns", "Effects", "Sweet Berry Thorns", "Controls sweet berry thorns behavior.", false);
        add(values, "pumpkinPieEnabled", "Food Sets", "Pumpkin Pie", "Controls pumpkin pie behavior.", false);
        add(values, "pumpkinPieArmorEffects", "Effects", "Pumpkin Pie Armor", "Controls pumpkin pie armor behavior.", false);
        add(values, "pumpkinPieEndermanAvoidance", "Effects", "Pumpkin Pie Enderman Avoidance", "Controls pumpkin pie enderman avoidance behavior.", false);
        add(values, "mushroomEnabled", "Food Sets", "Mushroom", "Controls mushroom behavior.", false);
        add(values, "mushroomArmorEffects", "Effects", "Mushroom Armor", "Controls mushroom armor behavior.", false);
        add(values, "mushroomSporeCloud", "Food Sets", "Mushroom Spore Cloud", "Controls mushroom spore cloud behavior.", false);
        add(values, "pufferfishEnabled", "Food Sets", "Pufferfish", "Controls pufferfish behavior.", false);
        add(values, "pufferfishArmorEffects", "Effects", "Pufferfish Armor", "Controls pufferfish armor behavior.", false);
        add(values, "pufferfishPoisonAura", "Food Sets", "Pufferfish Poison Aura", "Controls pufferfish poison aura behavior.", false);
        add(values, "honeyEnabled", "Food Sets", "Honey", "Controls honey behavior.", false);
        add(values, "honeyArmorEffects", "Effects", "Honey Armor", "Controls honey armor behavior.", false);
        add(values, "honeySticky", "Effects", "Honey Sticky", "Controls honey sticky behavior.", false);
        add(values, "chorusFruitEnabled", "Food Sets", "Chorus Fruit", "Controls chorus fruit behavior.", false);
        add(values, "chorusFruitArmorEffects", "Effects", "Chorus Fruit Armor", "Controls chorus fruit armor behavior.", false);
        add(values, "chorusFruitTeleport", "Effects", "Chorus Fruit Teleport", "Controls chorus fruit teleport behavior.", false);
        add(values, "goldenAppleEnabled", "Food Sets", "Golden Apple", "Controls golden apple behavior.", false);
        add(values, "goldenAppleArmorEffects", "Effects", "Golden Apple Armor", "Controls golden apple armor behavior.", false);
        add(values, "ectoplasmSetEnabled", "Content Sets", "Ectoplasm Set", "Controls ectoplasm set behavior.", false);
        add(values, "opToolEffectsEnabled", "Content Sets", "Op Tool", "Controls op tool behavior.", false);
        add(values, "opArmorEffectsEnabled", "Content Sets", "Op Armor", "Controls op armor behavior.", false);
        add(values, "ghostSpawnChance", "Effects", "Ghost Spawn Chance", "Controls ghost spawn chance behavior.", false);
        add(values, "wraithSpawnChance", "Effects", "Wraith Spawn Chance", "Controls wraith spawn chance behavior.", false);
        add(values, "controlledDrops", "Content Sets", "Controlled Drops", "Controls controlled drops behavior.", false);
        add(values, "controlledEntityDamage", "Effects", "Controlled Entity Damage", "Controls controlled entity damage behavior.", false);
        add(values, "remoteRange", "Effects", "Remote Range", "Controls remote range behavior.", false);
        add(values, "snowMeltEffects", "Effects", "Snow Melt", "Controls snow melt behavior.", false);
        add(values, "iceEffects", "Effects", "Ice", "Controls ice behavior.", false);
        add(values, "pprismWaterEffects", "Effects", "Pprism Water", "Controls pprism water behavior.", false);
        add(values, "fniFireEffects", "Effects", "Fni Fire", "Controls fni fire behavior.", false);
        add(values, "coalFireEffects", "Effects", "Coal Fire", "Controls coal fire behavior.", false);
        add(values, "cakeHungerEffects", "Effects", "Cake Hunger", "Controls cake hunger behavior.", false);
        add(values, "cakeArmorEffects", "Effects", "Cake Armor", "Controls cake armor behavior.", false);
        add(values, "ectoplasmGhostAvoidance", "Effects", "Ectoplasm Ghost Avoidance", "Controls ectoplasm ghost avoidance behavior.", false);
        add(values, "ectoplasmWallPhasing", "Effects", "Ectoplasm Wall Phasing", "Controls ectoplasm wall phasing behavior.", false);
        if (values.size() != 126) throw new IllegalStateException("Expected 126 config descriptors");
        return Collections.unmodifiableMap(values);
    }

    private static void add(Map<String, Descriptor> values, String key, String category,
                            String label, String tooltip, boolean reloadRequired) {
        if (values.put(key, new Descriptor(key, category, label, tooltip, reloadRequired)) != null) {
            throw new IllegalStateException("Duplicate config descriptor: " + key);
        }
    }
}
