modLoader = "javafml"
loaderVersion = "[4,)"
license = "CC0-1.0"

[[mods]]
modId = "usefultoolsmod"
version = "${version}"
displayName = "The Useful Tools Mod"
authors = "stonytark_mkii"
description = '''
A simple mod adding various tools and armor based on reinforced versions of common materials.
'''
displayURL = "https://www.curseforge.com/minecraft/mc-mods/the-useful-tools-mod"
issueTrackerURL = "https://github.com/StonyTark1117/UsefulToolsMod/issues"

[[dependencies.usefultoolsmod]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.usefultoolsmod]]
modId = "jei"
type = "optional"
versionRange = "[19.0.0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.usefultoolsmod]]
modId = "waila"
type = "optional"
versionRange = "[12.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.usefultoolsmod]]
modId = "jeresources"
type = "optional"
versionRange = "[1.6.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.usefultoolsmod]]
modId = "magnetization"
type = "optional"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.usefultoolsmod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.usefultoolsmod]]
modId = "architectury"
type = "required"
versionRange = "[13.0.0,)"
ordering = "AFTER"
side = "BOTH"
