// Generated by scripts/generate_classic_catalog.py. Do not edit manually.
package com.stonytark.usefultoolsmod.classic;

import java.io.File;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import net.minecraftforge.common.config.ConfigElement;
import net.minecraftforge.common.config.Configuration;
import cpw.mods.fml.client.config.IConfigElement;

public final class ClassicGeneratedConfig {
    private static final Map<String, Object> VALUES = new LinkedHashMap<String, Object>();
    private static Configuration configuration;
    private ClassicGeneratedConfig() {}

    public static void load(File file) {
        configuration = new Configuration(file);
        configuration.load();
        VALUES.put("explosivesEnabled", configuration.get("Content Sets", "explosivesEnabled", true, "Controls explosives behavior.").getBoolean(true));
        VALUES.put("obsidianEnabled", configuration.get("Content Sets", "obsidianEnabled", true, "Controls obsidian behavior.").getBoolean(true));
        VALUES.put("emeraldEnabled", configuration.get("Content Sets", "emeraldEnabled", true, "Controls emerald behavior.").getBoolean(true));
        VALUES.put("lapisEnabled", configuration.get("Content Sets", "lapisEnabled", true, "Controls lapis behavior.").getBoolean(true));
        VALUES.put("ferrousGoldEnabled", configuration.get("Content Sets", "ferrousGoldEnabled", true, "Controls ferrous gold behavior.").getBoolean(true));
        VALUES.put("hardenedRedstoneEnabled", configuration.get("Content Sets", "hardenedRedstoneEnabled", true, "Controls hardened redstone behavior.").getBoolean(true));
        VALUES.put("hardenedGlowstoneEnabled", configuration.get("Content Sets", "hardenedGlowstoneEnabled", true, "Controls hardened glowstone behavior.").getBoolean(true));
        VALUES.put("overpowerEnabled", configuration.get("Content Sets", "overpowerEnabled", true, "Controls overpower behavior.").getBoolean(true));
        VALUES.put("ghostEnabled", configuration.get("Content Sets", "ghostEnabled", true, "Controls ghost behavior.").getBoolean(true));
        VALUES.put("spectralInfuserEnabled", configuration.get("Content Sets", "spectralInfuserEnabled", true, "Controls spectral infuser behavior.").getBoolean(true));
        VALUES.put("wraithEnabled", configuration.get("Content Sets", "wraithEnabled", true, "Controls wraith behavior.").getBoolean(true));
        VALUES.put("soulLanternEnabled", configuration.get("Content Sets", "soulLanternEnabled", true, "Controls soul lantern behavior.").getBoolean(true));
        VALUES.put("spectralResonatorEnabled", configuration.get("Content Sets", "spectralResonatorEnabled", true, "Controls spectral resonator behavior.").getBoolean(true));
        VALUES.put("miningChargeEnabled", configuration.get("Content Sets", "miningChargeEnabled", true, "Controls mining charge behavior.").getBoolean(true));
        VALUES.put("stickyDynamiteEnabled", configuration.get("Content Sets", "stickyDynamiteEnabled", true, "Controls sticky dynamite behavior.").getBoolean(true));
        VALUES.put("remoteDetonationEnabled", configuration.get("Content Sets", "remoteDetonationEnabled", true, "Controls remote detonation behavior.").getBoolean(true));
        VALUES.put("infusedToolEffects", configuration.get("Effects", "infusedToolEffects", true, "Controls infused tool behavior.").getBoolean(true));
        VALUES.put("rawMetalRoughEnabled", configuration.get("Content Sets", "rawMetalRoughEnabled", true, "Controls raw metal rough behavior.").getBoolean(true));
        VALUES.put("roughCrystalEnabled", configuration.get("Content Sets", "roughCrystalEnabled", true, "Controls rough crystal behavior.").getBoolean(true));
        VALUES.put("snowEnabled", configuration.get("Content Sets", "snowEnabled", true, "Controls snow behavior.").getBoolean(true));
        VALUES.put("polishedCrystalEnabled", configuration.get("Content Sets", "polishedCrystalEnabled", true, "Controls polished crystal behavior.").getBoolean(true));
        VALUES.put("iceEnabled", configuration.get("Content Sets", "iceEnabled", true, "Controls ice behavior.").getBoolean(true));
        VALUES.put("pprismEnabled", configuration.get("Content Sets", "pprismEnabled", true, "Controls pprism behavior.").getBoolean(true));
        VALUES.put("flintEnabled", configuration.get("Content Sets", "flintEnabled", true, "Controls flint behavior.").getBoolean(true));
        VALUES.put("fniEnabled", configuration.get("Content Sets", "fniEnabled", true, "Controls fni behavior.").getBoolean(true));
        VALUES.put("woodVariantsEnabled", configuration.get("Content Sets", "woodVariantsEnabled", true, "Controls wood variants behavior.").getBoolean(true));
        VALUES.put("stoneVariantsEnabled", configuration.get("Content Sets", "stoneVariantsEnabled", true, "Controls stone variants behavior.").getBoolean(true));
        VALUES.put("paperEnabled", configuration.get("Content Sets", "paperEnabled", true, "Controls paper behavior.").getBoolean(true));
        VALUES.put("paperEffects", configuration.get("Effects", "paperEffects", true, "Controls paper behavior.").getBoolean(true));
        VALUES.put("featherEnabled", configuration.get("Content Sets", "featherEnabled", true, "Controls feather behavior.").getBoolean(true));
        VALUES.put("featherEffects", configuration.get("Effects", "featherEffects", true, "Controls feather behavior.").getBoolean(true));
        VALUES.put("glassEnabled", configuration.get("Content Sets", "glassEnabled", true, "Controls glass behavior.").getBoolean(true));
        VALUES.put("glassEffects", configuration.get("Effects", "glassEffects", true, "Controls glass behavior.").getBoolean(true));
        VALUES.put("rabbitHideEnabled", configuration.get("Content Sets", "rabbitHideEnabled", true, "Controls rabbit hide behavior.").getBoolean(true));
        VALUES.put("rabbitHideEffects", configuration.get("Effects", "rabbitHideEffects", true, "Controls rabbit hide behavior.").getBoolean(true));
        VALUES.put("cactusEnabled", configuration.get("Content Sets", "cactusEnabled", true, "Controls cactus behavior.").getBoolean(true));
        VALUES.put("cactusEffects", configuration.get("Effects", "cactusEffects", true, "Controls cactus behavior.").getBoolean(true));
        VALUES.put("spongeEnabled", configuration.get("Content Sets", "spongeEnabled", true, "Controls sponge behavior.").getBoolean(true));
        VALUES.put("spongeEffects", configuration.get("Effects", "spongeEffects", true, "Controls sponge behavior.").getBoolean(true));
        VALUES.put("boneEnabled", configuration.get("Content Sets", "boneEnabled", true, "Controls bone behavior.").getBoolean(true));
        VALUES.put("boneEffects", configuration.get("Effects", "boneEffects", true, "Controls bone behavior.").getBoolean(true));
        VALUES.put("clayEnabled", configuration.get("Content Sets", "clayEnabled", true, "Controls clay behavior.").getBoolean(true));
        VALUES.put("clayEffects", configuration.get("Effects", "clayEffects", true, "Controls clay behavior.").getBoolean(true));
        VALUES.put("netherWartEnabled", configuration.get("Content Sets", "netherWartEnabled", true, "Controls nether wart behavior.").getBoolean(true));
        VALUES.put("netherWartEffects", configuration.get("Effects", "netherWartEffects", true, "Controls nether wart behavior.").getBoolean(true));
        VALUES.put("brickEnabled", configuration.get("Content Sets", "brickEnabled", true, "Controls brick behavior.").getBoolean(true));
        VALUES.put("netherBrickEnabled", configuration.get("Content Sets", "netherBrickEnabled", true, "Controls nether brick behavior.").getBoolean(true));
        VALUES.put("netherBrickEffects", configuration.get("Effects", "netherBrickEffects", true, "Controls nether brick behavior.").getBoolean(true));
        VALUES.put("dripstoneEnabled", configuration.get("Content Sets", "dripstoneEnabled", true, "Controls dripstone behavior.").getBoolean(true));
        VALUES.put("dripstoneEffects", configuration.get("Effects", "dripstoneEffects", true, "Controls dripstone behavior.").getBoolean(true));
        VALUES.put("copperEnabled", configuration.get("Content Sets", "copperEnabled", true, "Controls copper behavior.").getBoolean(true));
        VALUES.put("copperEffects", configuration.get("Effects", "copperEffects", true, "Controls copper behavior.").getBoolean(true));
        VALUES.put("phantomEnabled", configuration.get("Content Sets", "phantomEnabled", true, "Controls phantom behavior.").getBoolean(true));
        VALUES.put("phantomEffects", configuration.get("Effects", "phantomEffects", true, "Controls phantom behavior.").getBoolean(true));
        VALUES.put("magmaCreamEnabled", configuration.get("Content Sets", "magmaCreamEnabled", true, "Controls magma cream behavior.").getBoolean(true));
        VALUES.put("magmaCreamEffects", configuration.get("Effects", "magmaCreamEffects", true, "Controls magma cream behavior.").getBoolean(true));
        VALUES.put("slimeEnabled", configuration.get("Content Sets", "slimeEnabled", true, "Controls slime behavior.").getBoolean(true));
        VALUES.put("slimeEffects", configuration.get("Effects", "slimeEffects", true, "Controls slime behavior.").getBoolean(true));
        VALUES.put("blazeEnabled", configuration.get("Content Sets", "blazeEnabled", true, "Controls blaze behavior.").getBoolean(true));
        VALUES.put("blazeEffects", configuration.get("Effects", "blazeEffects", true, "Controls blaze behavior.").getBoolean(true));
        VALUES.put("nautilusEnabled", configuration.get("Content Sets", "nautilusEnabled", true, "Controls nautilus behavior.").getBoolean(true));
        VALUES.put("nautilusEffects", configuration.get("Effects", "nautilusEffects", true, "Controls nautilus behavior.").getBoolean(true));
        VALUES.put("purpurEnabled", configuration.get("Content Sets", "purpurEnabled", true, "Controls purpur behavior.").getBoolean(true));
        VALUES.put("purpurEffects", configuration.get("Effects", "purpurEffects", true, "Controls purpur behavior.").getBoolean(true));
        VALUES.put("ghastTearEnabled", configuration.get("Content Sets", "ghastTearEnabled", true, "Controls ghast tear behavior.").getBoolean(true));
        VALUES.put("ghastTearEffects", configuration.get("Effects", "ghastTearEffects", true, "Controls ghast tear behavior.").getBoolean(true));
        VALUES.put("eyeOfEnderEnabled", configuration.get("Content Sets", "eyeOfEnderEnabled", true, "Controls eye of ender behavior.").getBoolean(true));
        VALUES.put("eyeOfEnderEffects", configuration.get("Effects", "eyeOfEnderEffects", true, "Controls eye of ender behavior.").getBoolean(true));
        VALUES.put("shulkerEnabled", configuration.get("Content Sets", "shulkerEnabled", true, "Controls shulker behavior.").getBoolean(true));
        VALUES.put("shulkerEffects", configuration.get("Effects", "shulkerEffects", true, "Controls shulker behavior.").getBoolean(true));
        VALUES.put("turtleScuteEnabled", configuration.get("Content Sets", "turtleScuteEnabled", true, "Controls turtle scute behavior.").getBoolean(true));
        VALUES.put("turtleScuteEffects", configuration.get("Effects", "turtleScuteEffects", true, "Controls turtle scute behavior.").getBoolean(true));
        VALUES.put("echoShardEnabled", configuration.get("Content Sets", "echoShardEnabled", true, "Controls echo shard behavior.").getBoolean(true));
        VALUES.put("echoShardEffects", configuration.get("Effects", "echoShardEffects", true, "Controls echo shard behavior.").getBoolean(true));
        VALUES.put("dragonBreathEnabled", configuration.get("Content Sets", "dragonBreathEnabled", true, "Controls dragon breath behavior.").getBoolean(true));
        VALUES.put("dragonBreathEffects", configuration.get("Effects", "dragonBreathEffects", true, "Controls dragon breath behavior.").getBoolean(true));
        VALUES.put("leatherEnabled", configuration.get("Content Sets", "leatherEnabled", true, "Controls leather behavior.").getBoolean(true));
        VALUES.put("coalEnabled", configuration.get("Content Sets", "coalEnabled", true, "Controls coal behavior.").getBoolean(true));
        VALUES.put("cakeEnabled", configuration.get("Food Sets", "cakeEnabled", true, "Controls cake behavior.").getBoolean(true));
        VALUES.put("foodHungerDrain", configuration.get("Effects", "foodHungerDrain", true, "Controls food hunger drain behavior.").getBoolean(true));
        VALUES.put("breadEnabled", configuration.get("Food Sets", "breadEnabled", true, "Controls bread behavior.").getBoolean(true));
        VALUES.put("breadArmorEffects", configuration.get("Effects", "breadArmorEffects", true, "Controls bread armor behavior.").getBoolean(true));
        VALUES.put("driedKelpEnabled", configuration.get("Food Sets", "driedKelpEnabled", true, "Controls dried kelp behavior.").getBoolean(true));
        VALUES.put("driedKelpArmorEffects", configuration.get("Effects", "driedKelpArmorEffects", true, "Controls dried kelp armor behavior.").getBoolean(true));
        VALUES.put("rottenFleshEnabled", configuration.get("Food Sets", "rottenFleshEnabled", true, "Controls rotten flesh behavior.").getBoolean(true));
        VALUES.put("rottenFleshArmorEffects", configuration.get("Effects", "rottenFleshArmorEffects", true, "Controls rotten flesh armor behavior.").getBoolean(true));
        VALUES.put("rottenFleshUndeadNeutral", configuration.get("Food Sets", "rottenFleshUndeadNeutral", true, "Controls rotten flesh undead neutral behavior.").getBoolean(true));
        VALUES.put("melonEnabled", configuration.get("Content Sets", "melonEnabled", true, "Controls melon behavior.").getBoolean(true));
        VALUES.put("melonArmorEffects", configuration.get("Effects", "melonArmorEffects", true, "Controls melon armor behavior.").getBoolean(true));
        VALUES.put("sweetBerryEnabled", configuration.get("Food Sets", "sweetBerryEnabled", true, "Controls sweet berry behavior.").getBoolean(true));
        VALUES.put("sweetBerryArmorEffects", configuration.get("Effects", "sweetBerryArmorEffects", true, "Controls sweet berry armor behavior.").getBoolean(true));
        VALUES.put("sweetBerryThorns", configuration.get("Effects", "sweetBerryThorns", true, "Controls sweet berry thorns behavior.").getBoolean(true));
        VALUES.put("pumpkinPieEnabled", configuration.get("Food Sets", "pumpkinPieEnabled", true, "Controls pumpkin pie behavior.").getBoolean(true));
        VALUES.put("pumpkinPieArmorEffects", configuration.get("Effects", "pumpkinPieArmorEffects", true, "Controls pumpkin pie armor behavior.").getBoolean(true));
        VALUES.put("pumpkinPieEndermanAvoidance", configuration.get("Effects", "pumpkinPieEndermanAvoidance", true, "Controls pumpkin pie enderman avoidance behavior.").getBoolean(true));
        VALUES.put("mushroomEnabled", configuration.get("Food Sets", "mushroomEnabled", true, "Controls mushroom behavior.").getBoolean(true));
        VALUES.put("mushroomArmorEffects", configuration.get("Effects", "mushroomArmorEffects", true, "Controls mushroom armor behavior.").getBoolean(true));
        VALUES.put("mushroomSporeCloud", configuration.get("Food Sets", "mushroomSporeCloud", true, "Controls mushroom spore cloud behavior.").getBoolean(true));
        VALUES.put("pufferfishEnabled", configuration.get("Food Sets", "pufferfishEnabled", true, "Controls pufferfish behavior.").getBoolean(true));
        VALUES.put("pufferfishArmorEffects", configuration.get("Effects", "pufferfishArmorEffects", true, "Controls pufferfish armor behavior.").getBoolean(true));
        VALUES.put("pufferfishPoisonAura", configuration.get("Food Sets", "pufferfishPoisonAura", true, "Controls pufferfish poison aura behavior.").getBoolean(true));
        VALUES.put("honeyEnabled", configuration.get("Food Sets", "honeyEnabled", true, "Controls honey behavior.").getBoolean(true));
        VALUES.put("honeyArmorEffects", configuration.get("Effects", "honeyArmorEffects", true, "Controls honey armor behavior.").getBoolean(true));
        VALUES.put("honeySticky", configuration.get("Effects", "honeySticky", true, "Controls honey sticky behavior.").getBoolean(true));
        VALUES.put("chorusFruitEnabled", configuration.get("Food Sets", "chorusFruitEnabled", true, "Controls chorus fruit behavior.").getBoolean(true));
        VALUES.put("chorusFruitArmorEffects", configuration.get("Effects", "chorusFruitArmorEffects", true, "Controls chorus fruit armor behavior.").getBoolean(true));
        VALUES.put("chorusFruitTeleport", configuration.get("Effects", "chorusFruitTeleport", true, "Controls chorus fruit teleport behavior.").getBoolean(true));
        VALUES.put("goldenAppleEnabled", configuration.get("Food Sets", "goldenAppleEnabled", true, "Controls golden apple behavior.").getBoolean(true));
        VALUES.put("goldenAppleArmorEffects", configuration.get("Effects", "goldenAppleArmorEffects", true, "Controls golden apple armor behavior.").getBoolean(true));
        VALUES.put("ectoplasmSetEnabled", configuration.get("Content Sets", "ectoplasmSetEnabled", true, "Controls ectoplasm set behavior.").getBoolean(true));
        VALUES.put("opToolEffectsEnabled", configuration.get("Content Sets", "opToolEffectsEnabled", true, "Controls op tool behavior.").getBoolean(true));
        VALUES.put("opArmorEffectsEnabled", configuration.get("Content Sets", "opArmorEffectsEnabled", true, "Controls op armor behavior.").getBoolean(true));
        VALUES.put("ghostSpawnChance", configuration.getFloat("ghostSpawnChance", "Effects", 0.15F, 0.0F, 1.0F, "Controls ghost spawn chance behavior."));
        VALUES.put("wraithSpawnChance", configuration.getFloat("wraithSpawnChance", "Effects", 0.0375F, 0.0F, 1.0F, "Controls wraith spawn chance behavior."));
        VALUES.put("controlledDrops", configuration.get("Content Sets", "controlledDrops", true, "Controls controlled drops behavior.").getBoolean(true));
        VALUES.put("controlledEntityDamage", configuration.getFloat("controlledEntityDamage", "Effects", 8.0F, 0.0F, 8.0F, "Controls controlled entity damage behavior."));
        VALUES.put("remoteRange", configuration.getFloat("remoteRange", "Effects", 128.0F, 16.0F, 1024.0F, "Controls remote range behavior."));
        VALUES.put("snowMeltEffects", configuration.get("Effects", "snowMeltEffects", true, "Controls snow melt behavior.").getBoolean(true));
        VALUES.put("iceEffects", configuration.get("Effects", "iceEffects", true, "Controls ice behavior.").getBoolean(true));
        VALUES.put("pprismWaterEffects", configuration.get("Effects", "pprismWaterEffects", true, "Controls pprism water behavior.").getBoolean(true));
        VALUES.put("fniFireEffects", configuration.get("Effects", "fniFireEffects", true, "Controls fni fire behavior.").getBoolean(true));
        VALUES.put("coalFireEffects", configuration.get("Effects", "coalFireEffects", true, "Controls coal fire behavior.").getBoolean(true));
        VALUES.put("cakeHungerEffects", configuration.get("Effects", "cakeHungerEffects", true, "Controls cake hunger behavior.").getBoolean(true));
        VALUES.put("cakeArmorEffects", configuration.get("Effects", "cakeArmorEffects", true, "Controls cake armor behavior.").getBoolean(true));
        VALUES.put("ectoplasmGhostAvoidance", configuration.get("Effects", "ectoplasmGhostAvoidance", true, "Controls ectoplasm ghost avoidance behavior.").getBoolean(true));
        VALUES.put("ectoplasmWallPhasing", configuration.get("Effects", "ectoplasmWallPhasing", true, "Controls ectoplasm wall phasing behavior.").getBoolean(true));
        if (configuration.hasChanged()) configuration.save();
    }

    public static boolean booleanValue(String key) {
        Object value = VALUES.get(key);
        return value instanceof Boolean && (Boolean) value;
    }

    public static double doubleValue(String key) {
        Object value = VALUES.get(key);
        return value instanceof Number ? ((Number) value).doubleValue() : 0.0D;
    }

    public static List<IConfigElement> elements() {
        List<IConfigElement> elements = new ArrayList<IConfigElement>();
        if (configuration == null) return elements;
        for (String category : configuration.getCategoryNames())
            elements.add(new ConfigElement(configuration.getCategory(category)));
        return elements;
    }
}
