#!/usr/bin/env python3
"""Generate the runtime config descriptor used by every modern config screen."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "catalog/useful_tools_catalog.json"
SOURCE_ROOTS = (
    "1.20.1/forge",
    "1.20.1/fabric",
    "1.20.1/neoforge",
    "1.20.2/forge",
    "1.20.2/fabric",
    "1.20.2/neoforge",
    "1.21.1/forge",
    "1.21.1/fabric",
    "1.21.1/neoforge",
    "26.1.2/forge",
    "26.1.2/fabric",
    "26.1.2/neoforge",
    "26.2/forge",
    "26.2/fabric",
    "26.2/neoforge",
)
RELATIVE_OUTPUT = Path(
    "src/main/java/com/stonytark/usefultoolsmod/client/ConfigDescriptors.java"
)


def java_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def render(options: list[dict[str, object]]) -> str:
    rows = "\n".join(
        "        add(values, %s, %s, %s, %s, %s);"
        % (
            java_string(str(option["key"])),
            java_string(str(option["category"])),
            java_string(str(option["label"])),
            java_string(str(option["tooltip"])),
            str(bool(option["reload_required"])).lower(),
        )
        for option in options
    )
    return f"""// Generated by scripts/generate_config_descriptors.py. Do not edit by hand.
package com.stonytark.usefultoolsmod.client;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/** Canonical, loader-neutral metadata for all 116 persistent config options. */
public final class ConfigDescriptors {{
    public record Descriptor(String key, String category, String label, String tooltip,
                             boolean reloadRequired) {{}}

    private static final Map<String, Descriptor> VALUES = build();

    private ConfigDescriptors() {{}}

    public static Descriptor get(String key) {{
        Descriptor descriptor = VALUES.get(key);
        if (descriptor == null) throw new IllegalArgumentException("Unknown config option: " + key);
        return descriptor;
    }}

    public static Map<String, Descriptor> values() {{
        return VALUES;
    }}

    private static Map<String, Descriptor> build() {{
        Map<String, Descriptor> values = new LinkedHashMap<>();
{rows}
        if (values.size() != 116) throw new IllegalStateException("Expected 116 config descriptors");
        return Collections.unmodifiableMap(values);
    }}

    private static void add(Map<String, Descriptor> values, String key, String category,
                            String label, String tooltip, boolean reloadRequired) {{
        if (values.put(key, new Descriptor(key, category, label, tooltip, reloadRequired)) != null) {{
            throw new IllegalStateException("Duplicate config descriptor: " + key);
        }}
    }}
}}
"""


def main() -> None:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    options = catalog["config"]
    if len(options) != 116:
        raise SystemExit(f"expected 116 config options, found {len(options)}")
    content = render(options)
    for root in SOURCE_ROOTS:
        target = ROOT / root / RELATIVE_OUTPUT
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        print(target.relative_to(ROOT))


if __name__ == "__main__":
    main()
