#!/usr/bin/env python3
"""Generate catalog-owned Java registration ID tables for every modern source root.

The catalog owns stable identifiers; loader-native classes continue to own the
factory expressions needed by their Minecraft API. ``--adopt`` is a one-time
mechanical migration that replaces duplicated ID literals in those factories
with references to the generated table.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "catalog/useful_tools_catalog.json"
MODERN_ROOTS = tuple(
    ROOT / version / loader
    for version in ("1.20.1", "1.20.2", "26.1.2", "26.2")
    for loader in ("forge", "fabric", "neoforge")
) + (ROOT / "1.21.1/common", ROOT / "1.21.1/forge-standalone")
JAVA_RELATIVE = Path(
    "src/main/java/com/stonytark/usefultoolsmod/generated/GeneratedRegistrationIds.java"
)
SOURCE_FILES = {
    "Items": Path("src/main/java/com/stonytark/usefultoolsmod/item/ModItems.java"),
    "Blocks": Path("src/main/java/com/stonytark/usefultoolsmod/block/ModBlocks.java"),
    "Entities": Path("src/main/java/com/stonytark/usefultoolsmod/entity/ModEntities.java"),
}


def java_name(identifier: str) -> str:
    name = re.sub(r"[^A-Za-z0-9_]", "_", identifier).upper()
    return f"ID_{name}" if name[:1].isdigit() else name


def catalog_ids(data: dict) -> dict[str, list[str]]:
    content = data["content"]
    return {
        "Items": sorted(content["items"]),
        "Blocks": sorted(content["blocks"]),
        "Entities": sorted(content["entities"]),
    }


def render(data: dict) -> str:
    sections = catalog_ids(data)
    lines = [
        "// Generated by scripts/generate_registration_tables.py; do not edit.",
        "package com.stonytark.usefultoolsmod.generated;",
        "",
        "/** Stable registry identifiers owned by catalog/useful_tools_catalog.json. */",
        "public final class GeneratedRegistrationIds {",
        "    private GeneratedRegistrationIds() {}",
    ]
    for section, identifiers in sections.items():
        lines.extend(("", f"    public static final class {section} {{", f"        private {section}() {{}}"))
        for identifier in identifiers:
            lines.append(f'        public static final String {java_name(identifier)} = "{identifier}";')
        lines.append("")
        lines.append("        public static final String[] ALL = {")
        for identifier in identifiers:
            lines.append(f"            {java_name(identifier)},")
        lines.extend(("        };", "    }"))
    lines.extend(("}", ""))
    return "\n".join(lines)


def adopt_source(path: Path, section: str, identifiers: list[str]) -> bool:
    text = path.read_text(encoding="utf-8")
    updated = text
    for identifier in sorted(identifiers, key=len, reverse=True):
        updated = updated.replace(
            f'"{identifier}"',
            f"GeneratedRegistrationIds.{section}.{java_name(identifier)}",
        )
    if updated == text:
        return False
    import_line = "import com.stonytark.usefultoolsmod.generated.GeneratedRegistrationIds;\n"
    if import_line not in updated:
        package_end = updated.index("\n", updated.index("package ")) + 1
        updated = updated[:package_end] + "\n" + import_line + updated[package_end:]
    path.write_text(updated, encoding="utf-8")
    return True


def generated_drift(data: dict) -> list[str]:
    expected = render(data)
    drift = []
    for source_root in MODERN_ROOTS:
        output = source_root / JAVA_RELATIVE
        if not output.exists() or output.read_text(encoding="utf-8") != expected:
            drift.append(str(output.relative_to(ROOT)))
    return drift


def adoption_errors(data: dict) -> list[str]:
    sections = catalog_ids(data)
    errors = []
    for source_root in MODERN_ROOTS:
        for section, relative in SOURCE_FILES.items():
            path = source_root / relative
            text = path.read_text(encoding="utf-8")
            referenced = set(re.findall(
                rf"GeneratedRegistrationIds\.{section}\.([A-Z0-9_]+)", text
            ))
            expected = {java_name(identifier) for identifier in sections[section]}
            if referenced != expected:
                missing = sorted(expected - referenced)
                extra = sorted(referenced - expected)
                errors.append(
                    f"{path.relative_to(ROOT)} generated-ID mismatch "
                    f"(missing={missing[:5]}, extra={extra[:5]})"
                )
            stale_literals = [identifier for identifier in sections[section] if f'"{identifier}"' in text]
            if stale_literals:
                errors.append(
                    f"{path.relative_to(ROOT)} retains catalog ID literals: {stale_literals[:5]}"
                )
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail instead of writing stale tables")
    parser.add_argument("--adopt", action="store_true", help="replace registry ID literals in loader factories")
    args = parser.parse_args()
    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    expected = render(data)

    if args.check:
        drift = generated_drift(data)
        errors = [f"registration table drift: {path}" for path in drift] + adoption_errors(data)
        if errors:
            for message in errors:
                print(message)
            return 1
        print(f"registration table audit: OK ({len(MODERN_ROOTS)} source roots)")
        return 0

    sections = catalog_ids(data)
    changed = 0
    adopted = 0
    for source_root in MODERN_ROOTS:
        output = source_root / JAVA_RELATIVE
        output.parent.mkdir(parents=True, exist_ok=True)
        if not output.exists() or output.read_text(encoding="utf-8") != expected:
            output.write_text(expected, encoding="utf-8")
            changed += 1
        if args.adopt:
            for section, relative in SOURCE_FILES.items():
                adopted += adopt_source(source_root / relative, section, sections[section])
    print(f"registration tables: {changed} generated, {adopted} registry sources adopted")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
